title: AI MBTI 채팅
email: mun_1201@naver.com
description: MBTI 유형별 AI 상담 전문가와 친구가 되고 채팅 할 수 있습니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mbtichat.info" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mun01180
github_username:  moony01

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag