title: MBTI AI CHAT
email: mun_1201@naver.com
description: >- # this means to ignore newlines until "baseurl:"
  You can become friends and chat with an AI counseling specialist based on your MBTI type.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

paginate: 10
per_page: 20
paginate_path: "/page/:num/"

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag